services:
  - type: web
    name: fastapi-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn index:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: PORT
        value: "10000"
